server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:file:./data/db/h2
    #url: jdbc:h2:mydb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  jpa:
    hibernate:
      ddl-auto: create #genera las tablas

logging:
  level:
    root: info
    org.springframework: info

user-props:
  re-email: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
  re-pass: ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^\w\d])[A-Za-z\d\W]{8,}$

jwt:
  secret:
    key: f47a89e5289d7c3b62af0e46d49bf4c95c4a4fda78b16d9e93f21b0c3da4f17d
  expire:
    time: 600000


