# Server properties
server:
  servlet:
    context-path: /ms-user
spring:
  application:
    name: ms-user
  profiles:
    active: h2
  jackson:
    serialization:
      write-dates-as-timestamps: false

springdoc:
  swagger-ui:
    enabled: true
